 export const languagesList = [
    { code: "af", name: "Afrikaans" },
    { code: "ar", name: "Arabic" },
    { code: "ar_EG", name: "Arabic (EGY)" },
    { code: "ar_AE", name: "Arabic (UAE)" },
    { code: "ar_LB", name: "Arabic (LBN)" },
    { code: "ar_MA", name: "Arabic (MAR)" },
    { code: "ar_QA", name: "Arabic (QAT)" },
    { code: "az", name: "Azerbaijani" },
    { code: "be", name: "Belarusian" },
    { code: "bn", name: "Bengali" },
    { code: "bn_IN", name: "Bengali (IND)" },
    { code: "bg", name: "Bulgarian" },
    { code: "ca", name: "Catalan" },
    { code: "cs", name: "Czech" },
    { code: "da", name: "Danish" },
    { code: "de_AT", name: "German (AUT)" },
    { code: "de_CH", name: "German (CHE)" },
    { code: "hr", name: "Croatian" },
    { code: "nl", name: "Dutch" },
    { code: "en", name: "English" },
    { code: "en_AE", name: "English (UAE)" },
    { code: "en_AU", name: "English (AUS)" },
    { code: "en_CA", name: "English (CAN)" },
    { code: "en_GB", name: "English (UK)" },
    { code: "en_GH", name: "English (GHA)" },
    { code: "en_IE", name: "English (IRL)" },
    { code: "en_IN", name: "English (IND)" },
    { code: "en_JM", name: "English (JAM)" },
    { code: "en_MY", name: "English (MYS)" },
    { code: "en_NZ", name: "English (NZL)" },
    { code: "en_QA", name: "English (QAT)" },
    { code: "en_SG", name: "English (SGP)" },
    { code: "en_US", name: "English (US)" },
    { code: "en_UG", name: "English (UGA)" },
    { code: "en_ZA", name: "English (ZAF)" },
    { code: "es", name: "Spanish" },
    { code: "es_AR", name: "Spanish (ARG)" },
    { code: "es_CL", name: "Spanish (CHL)" },
    { code: "es_CO", name: "Spanish (COL)" },
    { code: "es_CR", name: "Spanish (CRI)" },
    { code: "es_DO", name: "Spanish (DOM)" },
    { code: "es_EC", name: "Spanish (ECU)" },
    { code: "es_ES", name: "Spanish (SPA)" },
    { code: "es_HN", name: "Spanish (HND)" },
    { code: "es_MX", name: "Spanish (MEX)" },
    { code: "es_PA", name: "Spanish (PAN)" },
    { code: "es_PE", name: "Spanish (PER)" },
    { code: "es_UY", name: "Spanish (URY)" },
    { code: "fr", name: "French" },
    { code: "de", name: "German" },
    { code: "hi", name: "Hindi" },
    { code: "it", name: "Italian" },
    { code: "pt", name: "Portuguese" },
    { code: "tr", name: "Turkish" },
  ];